version: '2.3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - crypto-backend
    env_file: local.env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A crypto worker --app=cryptobot.celery:app --loglevel=info -B
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - crypto-backend
    env_file: local.env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cryptobot/uwsgi_params:/app/cryptobot/uwsgi_params
      - ./cryptobot/cryptobot_nginx.conf:/etc/nginx/conf.d/cryptobot_nginx.conf
      - ./static/:/app/static
    networks:
      - crypto-backend
    depends_on:
      - web

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    volumes:
      - crypto-db:/var/lib/postgresql
    networks:
      - crypto-backend
    env_file: local.env

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - crypto-redis:/data
    networks:
      - crypto-backend

volumes:
  crypto-db:
    driver: local
  crypto-redis:
    driver: local

networks:
  crypto-backend:
    driver: bridge
