# Generated by Django 2.1.4 on 2019-01-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markethistoric',
            name='value',
        ),
        migrations.RemoveField(
            model_name='socialhistoric',
            name='value',
        ),
        migrations.AddField(
            model_name='markethistoric',
            name='asks_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markethistoric',
            name='avg_transaction_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markethistoric',
            name='bids_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialhistoric',
            name='gtrends_top_7d',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='markethistoric',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type_of_rule',
            field=models.CharField(choices=[('BEL', 'below'), ('ABO', 'above'), ('CGA', 'change_above'), ('CGB', 'change_below'), ('CPA', 'change_perc_above'), ('CPB', 'change_perc_below'), ('MVP', 'max_value_perc'), ('MVE', 'max_value'), ('AHS', 'after_hours'), ('MBA', 'market_bot_above'), ('MBB', 'market_bot_below'), ('SBA', 'social_bot_above'), ('SBB', 'social_bot_below')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=19),
        ),
    ]
