# Generated by Django 2.2.7 on 2020-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="type_of_rule",
            field=models.CharField(
                choices=[
                    ("BEL", "below"),
                    ("ABO", "above"),
                    ("CGA", "change_above"),
                    ("CGB", "change_below"),
                    ("CPA", "change_perc_above"),
                    ("CPB", "change_perc_below"),
                    ("AHS", "after_minutes"),
                    ("MBA", "market_bot_above"),
                    ("MBB", "market_bot_below"),
                    ("SBA", "social_bot_above"),
                    ("SBB", "social_bot_below"),
                    ("EXL", "execution_limit"),
                ],
                max_length=3,
            ),
        ),
    ]
