# Generated by Django 2.2.6 on 2019-10-28 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20190113_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='crypto',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='markethistoric',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type_of_rule',
            field=models.CharField(choices=[('BEL', 'below'), ('ABO', 'above'), ('CGA', 'change_above'), ('CGB', 'change_below'), ('CPA', 'change_perc_above'), ('CPB', 'change_perc_below'), ('AHS', 'after_minutes'), ('MBA', 'market_bot_above'), ('MBB', 'market_bot_below'), ('SBA', 'social_bot_above'), ('SBB', 'social_bot_below')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='crypto.CryptoModel'),
        ),
        migrations.AlterField(
            model_name='socialhistoric',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('rule_set', 'type_of_rule')},
        ),
    ]
