# Generated by Django 2.2.7 on 2020-10-30 18:01

from django.db import migrations


def create_cryptos(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CryptoModel = apps.get_model("crypto", "CryptoModel")
    CryptoModel.objects.using(db_alias).create(
        short_name="BTC", long_name="Bitcoin",
    )
    CryptoModel.objects.using(db_alias).create(
        short_name="ETH", long_name="Ethereum",
    )
    CryptoModel.objects.using(db_alias).create(
        short_name="XRP", long_name="Ripple",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0002_auto_20201019_1753"),
    ]

    operations = [
        migrations.RunPython(create_cryptos),
    ]
